# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

  
# Azure DevOps self hosted agents, VM pool
pool:
  name: Default

#Global settings
variables:
- group: CCH-1

# Path to local folder on HOST from pool where is UFT Launcher
- name: UFT_LAUNCHER
  value: 'C:\UFT_Launcher\UFT\UFTWorking'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Remove-Item "C:\UFT_Launcher\UFT\UFTWorking\res\Report*" -Recurse -Force

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Remove-Item "D:\Demo\Demo_1\Report*" -Recurse -Force
      Remove-Item "D:\Demo\Demo_2\Report*" -Recurse -Force


- task: RunFromFileSystemTask@5
  inputs:
    testPathInput: |
      d:\demo_1\demo
      d:\demo_2\demo
    uploadArtifact: 'no'
    mcAuthType: 'basic'


# JOB UFT/ALM Reporte 
- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit #     'JUnit'
    testResultsFiles: '**/*.xml'
    searchFolder: 'C:\UFT_Launcher\UFT\UFTWorking\res\Report_$(Build.BuildNumber)'
    testRunTitle: '$(System.DefinitionName)_$(Build.BuildNumber)'


- task: PublishReleaseArtifact@1
  inputs:
    artifactPath: 'd:\demo\demo1'